version: '3'

services:
  web:
    build: .
    command: gunicorn skagit60.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - db:/code/db/
      - static:/code/staticfiles
      - media:/code/mediafiles
      - nginx_logs:/code/nginx/logs
      - fonts:/code/fonts
    expose:
      - 8000
    restart: unless-stopped

  nginx:
    build:
      ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - certs:/etc/letsencrypt/
    - nginx_conf:/etc/nginx/
    - static:/code/staticfiles
    - media:/code/mediafiles
    - nginx_logs:/home/nginx_logs/
    - fonts:/code/fonts
    depends_on:
      - web
    restart: unless-stopped


volumes:
  db:
  certs:
  nginx_conf:
  nginx_logs:
  static:
  media:
  fonts: