version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.docker

  web:
    build: .
    command: gunicorn skagit60.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build:
      ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    - certs:/etc/letsencrypt/
    - nginx_conf:/etc/nginx/
    depends_on:
      - web
    env_file:
      - ./.env.docker

volumes:
  postgres_data:
  certs:
  nginx_conf: