[project]
name = "skagit60"
version = "0.1.0"
description = "A site for tracking trip reports."
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = "~=3.9"
license = "MIT"
dependencies = [
    "Django",
    "django-cleanup",
    "django-crispy-forms",
    "djangorestframework",
    "pandas",
    "dj-database-url",
    "whitenoise",
    "boto3",
    "django-storages",
    "psycopg2-binary",
    "setuptools>=75.8.0",
    "pillow>=11.1.0",
    "django-extensions>=3.2.3",
    "crispy-bootstrap4>=2024.10",
    "mangum>=0.19.0",
]

[dependency-groups]
dev = [
    "pytest>=7.1.1,<8",
    "pytest-django>=4.5.2,<5",
    "pytest-xdist>=2.5.0,<3",
    "factory-boy>=3.2.1,<4",
    "coverage>=6.3.2,<7",
    "pulumi>=3.152.0",
    "pulumi-aws>=6.69.0",
    "pre-commit>=4.1.0",
    "pulumi-awsx>=2.21.0",
    "pulumi-command>=1.0.2",
    "pulumi-random>=4.17.0",
    # Add with `pulumi package add terraform-provider supabase/supabase`
    "pulumi-supabase",
    "httpx>=0.28.1",
    "rich>=13.9.4",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "skagit60.settings"

[tool.uv.sources]
pulumi-supabase = { path = "infra/sdks/supabase" }

