# Generated by Django 3.0.2 on 2020-01-07 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('elevation', models.PositiveIntegerField()),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('long', models.DecimalField(decimal_places=5, max_digits=8)),
                ('peakbagger_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report', models.TextField(null=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('peak', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Peak')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalClimbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.TripReport')),
            ],
        ),
    ]
