# Generated by Django 3.0.2 on 2020-01-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='peak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Peak'),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('trip_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.TripReport')),
            ],
        ),
    ]
