# Generated by Django 3.0.2 on 2020-01-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200109_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
