# Generated by Django 3.0.2 on 2020-01-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200122_0709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportImages',
            new_name='ReportImage',
        ),
    ]
