# Generated by Django 3.0.2 on 2020-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200123_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
