# Generated by Django 3.0.2 on 2020-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200124_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/trip_reports'),
        ),
    ]
