# Generated by Django 3.0.2 on 2020-01-27 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0005_auto_20200125_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestedParticipant',
            new_name='InterestedClimber',
        ),
    ]
