# Generated by Django 3.0.2 on 2020-01-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200127_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestedclimber',
            name='message',
        ),
    ]
