# Generated by Django 3.0.2 on 2020-01-28 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_interestedclimber_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='trip_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.TripReport'),
            preserve_default=False,
        ),
    ]
